# DO500 Instructor Slides

### Full setup

Some reveal.js features, like external Markdown and speaker notes, require that
presentations run from a local web server. The following instructions will set
up such a server as well as all of the development tasks needed to make edits to
the reveal.js source code.

1. Install http://nodejs.org/[Node.js] (4.0.0 or later)

2. Clone the reveal.js repository
[source, sh]
[user@host path]$ git clone https://github.com/rht-labs/enablement-docs

3. Navigate to the slides folder
[source, sh]
[user@host path]$ cd slides

4. Install `npm` dependencies:
[source, sh]
[user@host path]$ npm install

1. Serve the presentation and monitor source files for changes:
[source, sh]
[user@host path]$ npm start

1. Open <http://localhost:8000> to view your presentation.  You can change the
port by using:
[source, sh]
[user@host path]$ npm start -- --port=8001

### Folder Structure

- **css/** Core styles without which the project does not function
- **js/** Like above but for JavaScript
- **plugin/** Components that have been developed as extensions to reveal.js
- **lib/** All other third party assets (JavaScript, CSS, fonts)

### Printing to PDF

1. Run the slides locally as described above.
2. Open the slides in Chrome or Chromium.
3. Add `?print-pdf` to the URL. For example: `http://localhost:8000/chapter17.html?print-pdf#/`
4. use Headless Chrome to download the pdf by using 
[source, sh]
for i in `seq 1 9`;
do
    $GOOGLE_CRHOME_PATH --headless --disable-gpu --print-to-pdf=./chapter0$i.pdf http://localhost:8000/chapter0$i.html\?print-pdf\#/
done
for i in `seq 10 17`;
do
    $GOOGLE_CHROME_PATH --headless --disable-gpu --print-to-pdf=./chapter$i.pdf http://localhost:8000/chapter$i.html\?print-pdf\#/
done

if you are using macOS the Google Chrome path is in 
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome`

### Deploy in OCP

This section includes a procedure to build a container image locally, publish it to an external image registry and run this new container image in Openshift. The main objetive is to make accessible the do500 slides though an Openshift Application. 

Before starting, please take special attention to the following requirements:

* An OCP Cluster installed and be logged with a project admin user
* A quay.io or another external image repository account with _push_ rights (*It is also required to push this new image in a publish repository)
* Podman installed in your laptop 

Once the requirements have been met, it is time to execute the following steps:

1. Clone the reveal.js repository
[source, sh]
[user@host path]$ git clone https://github.com/rht-labs/enablement-docs

2. Navigate to the slides folder
[source, sh]
[user@host path]$ cd slides

3. Modify params in _deploy_slides_ocp.sh_ script
[source, sh]
[user@host path]$ vi _deploy_slides_ocp.sh_
# Params
REGISTRY_SERVER=xxxxx
REGISTRY_PROJECT=xxxx
...
VERSION=xxxx
...

4. Execute _deploy_slides_ocp.sh_ script
[source, sh]
[user@host path]$ sh deploy_slides_ocp.sh
STEP 1: FROM quay.io/fedora/fedora:32-x86_64
STEP 2: RUN dnf install -y git npm bzip2
--> Using cache a32c8255e2ca1792c52b6ab5b79a2a0ef71cbc5396b7c5ef96dece76035e31da
--> a32c8255e2c
STEP 3: ADD . /slides/
--> aa8f2614ed5
STEP 4: WORKDIR /slides
--> 342693824e3
...
...
...
NAME           HOST/PORT                                            PATH   SERVICES       PORT       TERMINATION   WILDCARD
slides         slides-do500.apps.labs.sandbox37.opentlc.com                slides         8000-tcp                 None

NOTE: It is important to increment the image version every new build in order to have change and version control 

Once the process is finished, the script displays the public Openshift Application route (e.g. http://slides-do500.apps.labs.sandbox37.opentlc.com) which can be used to access slides via web browser.

It is important to bear in mind that it is possible to run this procedure several times and it will update the slides automatically every time.
